version: '3.8'

services:
  ph-api:
    container_name: ph-api
    environment:
      ConnectionStrings:postgres: host=ph-pg; port=5432; database=pharma_service; username=app; password=password;
      Serilog:WriteTo:0:Name: Console
      Serilog:WriteTo:0:Args:formatter: Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
    build:
      context: .
      dockerfile: src/PharmaService.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - ph-migrator
        
  ph-admin-client:
    container_name: ph-admin-client
    environment:
      WebShopApi:BaseAddress: http://ph-api
    ports:
      - "9080:80"
    build:
      context: .
      dockerfile: src/PharmaService.Admin.Client/Dockerfile
    depends_on:
      - ph-api
  
  ph-migrator:
    container_name: ph-migrator
    environment:
      ConnectionStrings:postgres: host=ph-pg; port=5432; database=pharma_service; username=app; password=password;
      Serilog:WriteTo:0:Name: Console
      Serilog:WriteTo:0:Args:formatter: Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
    build:
      context: .
      dockerfile: src/PharmaService.Migrator/Dockerfile
    depends_on:
      - ph-pg

  ph-pg:
    container_name: ph-pg
    image: postgres
    environment:
      POSTGRES_MULTIPLE_DATABASES: pharma_service
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - './data:/var/lib/postgresql/data'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 5s
      interval: 3s
      retries: 10
      timeout: 30s